name         'bigcommerce-nginx'
version      '0.0.4'
license      'MIT'
summary      'Install and manage nginx'
description  'A different approach to managing nginx sites available/enabled, and configuration includes. Requires Nginx 1.1.11+'
author       'Chris Boulton <chris@chrisboulton.com>'
source       'https://github.com/bigcommerce/puppet-nginx'
project_page 'https://github.com/bigcommerce/puppet-nginx'
